version: '3'
services:
  notebook:
    build: .
    ports: [8888:8888]
    environment:
      - JUPYTER_TOKEN=data

  db:
    image: postgres
    environment:
      - POSTGRES_USER=jupe
      - POSTGRES_PASSWORD=sekrit
    volumes:
      - ./data/in:/data/in:ro
      - ./data/out:/data/out
      - ./_/pg:/var/lib/postgresql/data
