version: '3'
services:
  notebook:
    build: .
    ports: [8888:8888]
    environment:
      - JUPYTER_TOKEN=data
    volumes:
      - ./_/jupyter:/home/jovyan

  db:
    image: postgres
    environment:
      - POSTGRES_USER=jupe
      - POSTGRES_PASSWORD=sekrit
    volumes:
      - ./_/jupyter/data:/data/in:ro
      - ./_/jupyter/data:/data/out
      - ./_/pg:/var/lib/postgresql/data
